apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  ports:
    - name: "3334"
      port: 3334
      targetPort: 3334
    - name: "3335"
      port: 3335
      targetPort: 3335
    - name: "3336"
      port: 3336
      targetPort: 3336
    - name: "2220"
      port: 2220
      targetPort: 2220
  selector:
    io.kompose.service: consumer
