apiVersion: v1
data:
  consumer.yml: "endpoints:\n  - chain-id: LAV1\n    api-interface: tendermintrpc\n    network-address: 0.0.0.0:3334\n  # - chain-id: LAV1\n  #   api-interface: rest\n  #   network-address: 0.0.0.0:3336\n  # - chain-id: LAV1\n  #   api-interface: grpc\n  #   network-address: 0.0.0.0:3335\n  - chain-id: SUIJSONRPC  \n    api-interface: jsonrpc  \n    network-address: 0.0.0.0:2220\nmetrics-listen-address: \":7779\"\n\n\n\n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: consumer
  name: consumer-cm0
