apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: indexer
  name: indexer
spec:
  containers:
    - env:
        - name: CHECKPOINT_DIR
          value: /checkpoints_indexer
        - name: DATABASE_URL
          value: postgres://supabase_admin:sui-indexer@db:5432/postgres?options=--search_path%3Dsui_indexer
        - name: LOCAL_MODE
          value: "true"
        - name: PIPELINE_BLOBS_BATCH_SIZE
          value: "10"
        - name: PIPELINE_BLOBS_RETRY_DELAY_MS
          value: "1000"
        - name: PIPELINE_BLOBS_WORKERS
          value: "1"
        - name: REMOTE_STORE_URL
          value: https://checkpoints.testnet.sui.io
        - name: RUST_LOG
          value: info
        - name: START_CHECKPOINT
          value: "94634"
      image: indexer
      name: indexer
  restartPolicy: OnFailure
