apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: lava-node
  name: lava-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lava-node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: lava-node
    spec:
      containers:
        - args:
            - start
            - --pruning=nothing
          image: ghcr.io/lavanet/lava/lavad:v5.2.1
          livenessProbe:
            exec:
              command:
                - lavad
                - status
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          name: lava-node
          ports:
            - containerPort: 1317
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 26656
              protocol: TCP
            - containerPort: 26657
              protocol: TCP
          volumeMounts:
            - mountPath: /lava
              name: lava-data
      restartPolicy: Always
      volumes:
        - name: lava-data
          persistentVolumeClaim:
            claimName: lava-data
