apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: meta
  name: meta
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meta
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: meta
    spec:
      containers:
        - env:
            - name: PG_META_DB_HOST
              value: db
            - name: PG_META_DB_NAME
              value: postgres
            - name: PG_META_DB_PASSWORD
              value: sui-indexer
            - name: PG_META_DB_PORT
              value: "5432"
            - name: PG_META_DB_USER
              value: supabase_admin
            - name: PG_META_PORT
              value: "8080"
          image: supabase/postgres-meta:v0.86.1
          name: supabase-meta
      restartPolicy: Always
