apiVersion: v1
data:
  fullchain.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFJDCCBAygAwIBAgISBarlzvqACTKe/H/pge2dRUHvMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTEwHhcNMjUwNDA3MTYwMDAzWhcNMjUwNzA2MTYwMDAyWjAcMRowGAYDVQQD
    ExFzdWkub2JzdWlkaWFuLnh5ejCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBALLbWhkfjKZu2brWVECb20aAWCYXTS2go8ru4x0GCK4sZFZooFe8Jo00CCVO
    pwL+HIJPLQTkWBDwvbZ+emFGlPOwYrjqAMkGPCfwYF9ci81mao5YB3z3zX8pokPk
    467PypmKdoyMfRlPg8b4rWV/f8DOesY5+Zwib9JOyQrmRMEccjlICFpnBN3K+lXa
    ZOn+uytU+WM5wKhqaakuy8MdJwhUPH6XooDZoNnx6UpYDjtSpR6w90bit4NU8tR2
    1ZQ7tUogyR+/MY7Uhd+FA54mpdoGdBfzsVPug3Hk9ZRUUIQ+4KMDIENoRwTuTgzD
    8ATnJDKq9j4hYA0xrSdt8hr03U8CAwEAAaOCAkcwggJDMA4GA1UdDwEB/wQEAwIF
    oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAd
    BgNVHQ4EFgQUy/isyuW5F/DuBndoJiUwm/IbRZswHwYDVR0jBBgwFoAUxc9GpOr0
    w8B6bJXELbBeki8m47kwVwYIKwYBBQUHAQEESzBJMCIGCCsGAQUFBzABhhZodHRw
    Oi8vcjExLm8ubGVuY3Iub3JnMCMGCCsGAQUFBzAChhdodHRwOi8vcjExLmkubGVu
    Y3Iub3JnLzAcBgNVHREEFTATghFzdWkub2JzdWlkaWFuLnh5ejATBgNVHSAEDDAK
    MAgGBmeBDAECATAvBgNVHR8EKDAmMCSgIqAghh5odHRwOi8vcjExLmMubGVuY3Iu
    b3JnLzExMi5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwCkQsUGSWBhVI8P
    1Oqc+3otJkVNh6l/L99FWfYnTzqEVAAAAZYRMH/7AAAEAwBIMEYCIQCdTyPwRba5
    tPGfOQ1MDkZ/gJUqduDkXBAso9jwBNWodwIhANfyPn5xJBye6eRX8ToftYyvnBa+
    WRWiLjjeXeSyVmGEAHYAEvFONL1TckyEBhnDjz96E/jntWKHiJxtMAWE6+WGJjoA
    AAGWETCADQAABAMARzBFAiEA6ZkzjiNRVmxwe0syRAS3KTRRxaPW5XgjdlmMxkj6
    VbICIBErAGTYDYTWe6MWPnZvoHHMhLJWa5E7iPJZPkqHdrF6MA0GCSqGSIb3DQEB
    CwUAA4IBAQAG/WfBiyNUAK5LFwpbkpRQPAJB+uhOnlglUgru3XRmeerdig4T69du
    8Ddqjsc1JsR8sl4JWjfwWdLJXBV0gSG13xUSmv/D9lcFo2MWtEACSsa7kur6GdKP
    pQck1kw7ttC0ouPV9Civq1MIpw5Xba3+sDuv052xdlOl0WV7PC9J+E/Dtea1drt6
    OCZVzkgdpVkhjQ7xbh3tt9hc6VFRyZ3QiyEXRQp+MpZqucFVeTGNYFh5iCYlujj/
    aoLp92uly7yxK6aZo29TGF/1lYO8Gkn6Pq5vnt+a2YtQAC2Dhw+TEf5RKC/sxWaB
    4YgpQwykLChQ2W9ecqbGkJKlcj4rH4Mb
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBjCCAu6gAwIBAgIRAIp9PhPWLzDvI4a9KQdrNPgwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDEMMAoGA1UEAxMDUjExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAuoe8XBsAOcvKCs3UZxD5ATylTqVhyybKUvsVAbe5KPUoHu0nsyQYOWcJ
    DAjs4DqwO3cOvfPlOVRBDE6uQdaZdN5R2+97/1i9qLcT9t4x1fJyyXJqC4N0lZxG
    AGQUmfOx2SLZzaiSqhwmej/+71gFewiVgdtxD4774zEJuwm+UE1fj5F2PVqdnoPy
    6cRms+EGZkNIGIBloDcYmpuEMpexsr3E+BUAnSeI++JjF5ZsmydnS8TbKF5pwnnw
    SVzgJFDhxLyhBax7QG0AtMJBP6dYuC/FXJuluwme8f7rsIU5/agK70XEeOtlKsLP
    Xzze41xNG/cLJyuqC0J3U095ah2H2QIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
    hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
    /wIBADAdBgNVHQ4EFgQUxc9GpOr0w8B6bJXELbBeki8m47kwHwYDVR0jBBgwFoAU
    ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
    hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
    A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
    AQELBQADggIBAE7iiV0KAxyQOND1H/lxXPjDj7I3iHpvsCUf7b632IYGjukJhM1y
    v4Hz/MrPU0jtvfZpQtSlET41yBOykh0FX+ou1Nj4ScOt9ZmWnO8m2OG0JAtIIE38
    01S0qcYhyOE2G/93ZCkXufBL713qzXnQv5C/viOykNpKqUgxdKlEC+Hi9i2DcaR1
    e9KUwQUZRhy5j/PEdEglKg3l9dtD4tuTm7kZtB8v32oOjzHTYw+7KdzdZiw/sBtn
    UfhBPORNuay4pJxmY/WrhSMdzFO2q3Gu3MUBcdo27goYKjL9CTF8j/Zz55yctUoV
    aneCWs/ajUX+HypkBTA+c8LGDLnWO2NKq0YD/pnARkAnYGPfUDoHR9gVSp/qRx+Z
    WghiDLZsMwhN1zjtSC0uBWiugF3vTNzYIEFfaPG7Ws3jDrAMMYebQ95JQ+HIBD/R
    PBuHRTBpqKlyDnkSHDHYPiNX3adPoPAcgdF3H2/W0rmoswMWgTlLn1Wu0mrks7/q
    pdWfS6PJ1jty80r2VKsM/Dj3YIDfbjXKdaFU5C+8bhfJGqU3taKauuz0wHVGT3eo
    6FlWkWYtbt4pgdamlwVeZEW+LM7qZEJEsMNPrfC03APKmZsJgpWCDWOKZvkZcvjV
    uYkQ4omYCTX5ohy+knMjdOmdH9c7SpqEWBDC86fiNex+O0XOMEZSa8DA
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm1
