apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: post-lava-node-init-claim6
  name: post-lava-node-init-claim6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
