apiVersion: v1
data:
  provider_lava.yml: "endpoints:\n  - api-interface: tendermintrpc\n    chain-id: LAV1\n    network-address:\n      address: \"0.0.0.0:3334\"\n      disable-tls: true\n    node-urls:\n      - url: ws://lava-node:26657/websocket\n      - url: http://lava-node:26657\n        # addons:\n        #   - archive\n  - api-interface: grpc\n    chain-id: LAV1\n    network-address:\n      address: \"0.0.0.0:3335\"\n      disable-tls: true\n    node-urls: \n      - url: lava-node:9090\n        # addons:\n        #   - archive\n  - api-interface: rest\n    chain-id: LAV1\n    network-address:\n      address: \"0.0.0.0:3336\"\n      disable-tls: true\n    node-urls: \n      - url: http://lava-node:1317\n        # addons:\n        #   - archive\n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: provider2
  name: provider2-cm0
