apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: sui-node
  name: sui-node
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8084"
      port: 8084
      protocol: UDP
      targetPort: 8084
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9184"
      port: 9184
      targetPort: 9184
  selector:
    io.kompose.service: sui-node
